### ISSUE TITLE
Bug - Erro ao criar o container pela primeira vez

### ISSUE THREAD

**Issue by leomedeiros1** [2019-2-arquitetura-desenho/monitoria-api#20]
## Descrição
Quando não se tem previamente uma imagem do docker, não é possível iniciar o servidor pela primeira vez.

## Passos Para Reproduzir o _Bug_
1 - Apague a imagem do docker, caso possua;
2 - Inicie a aplicacão com `make server`;
3 - Veja o erro;

<details>
  <summary>Erro completo:</summary>

```
monitoria-api    | Exception in thread django-main-thread:
monitoria-api    | Traceback (most recent call last):
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
monitoria-api    |     return self.cursor.execute(sql, params)
monitoria-api    | psycopg2.errors.UndefinedTable: relation "django_site" does not exist
monitoria-api    | LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...
monitoria-api    |                                                              ^
monitoria-api    | 
monitoria-api    | 
monitoria-api    | The above exception was the direct cause of the following exception:
monitoria-api    | 
monitoria-api    | Traceback (most recent call last):
monitoria-api    |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
monitoria-api    |     self.run()
monitoria-api    |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
monitoria-api    |     self._target(*self._args, **self._kwargs)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
monitoria-api    |     fn(*args, **kwargs)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
monitoria-api    |     self.check(display_num_errors=True)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
monitoria-api    |     include_deployment_checks=include_deployment_checks,
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
monitoria-api    |     return checks.run_checks(**kwargs)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
monitoria-api    |     new_errors = check(app_configs=app_configs)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
monitoria-api    |     return check_resolver(resolver)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
monitoria-api    |     return check_method()
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 399, in check
monitoria-api    |     for pattern in self.url_patterns:
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in get
monitoria-api    |     res = instance.dict[self.name] = self.func(instance)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 584, in url_patterns
monitoria-api    |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in get
monitoria-api    |     res = instance.dict[self.name] = self.func(instance)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
monitoria-api    |     return import_module(self.urlconf_name)
monitoria-api    |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
monitoria-api    |     return _bootstrap._gcd_import(name[level:], package, level)
monitoria-api    |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
monitoria-api    |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
monitoria-api    |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
monitoria-api    |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
monitoria-api    |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
monitoria-api    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
monitoria-api    |   File "/code/monitoria/urls.py", line 14, in <module>
monitoria-api    |     site = Site.objects.get(id=1)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
monitoria-api    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 402, in get
monitoria-api    |     num = len(clone)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 256, in len
monitoria-api    |     self._fetch_all()
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
monitoria-api    |     self._result_cache = list(self._iterable_class(self))
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 55, in iter
monitoria-api    |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
monitoria-api    |     cursor.execute(sql, params)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
monitoria-api    |     return super().execute(sql, params)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
monitoria-api    |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
monitoria-api    |     return executor(sql, params, many, context)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
monitoria-api    |     return self.cursor.execute(sql, params)
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in exit
monitoria-api    |     raise dj_exc_value.with_traceback(traceback) from exc_value
monitoria-api    |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
monitoria-api    |     return self.cursor.execute(sql, params)
monitoria-api    | django.db.utils.ProgrammingError: relation "django_site" does not exist
monitoria-api    | LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...
monitoria-api    |                                                              ^

```  
</details>

## Comportamento Esperado
* Que o servidor inicie corretamente

**Comment by andrelucax** [comment]
Ah, vejo que acabei cometendo um erro quando tinha feito a outra issue. Pelo jeito quando nao existe o Banco de Dados ainda ele nao cosegue mudar o domain e acaba dando um except sem tratamento, vou aproveitar essa issue e comecar com as variaveis de ambiente que serao necessarias e possibilita manter a outra issue feita

**Comment by WelisonR** [comment]
Issue fechada pelo PR #21.
